### ISSUE TITLE
running "npm i" causes "missing ) after argument list" error

### ISSUE THREAD

**Issue by Mnuzz** [plotly/dash-renderer#63]
OS: Windows 10
Commit: Latest master (25e4c566afb9d79685ba065e0a99ff4a00195d7a)
Node version: 8.9.4
npm version: 5.6.0

```

> dash-renderer@0.13.1 lint C:\dev\Daedalus\lib\dash-renderer
> eslint --quiet --fix .

npm info lifecycle dash-renderer@0.13.1~postlint: dash-renderer@0.13.1
npm info ok
npm info lifecycle dash-renderer@0.13.1~posttest: dash-renderer@0.13.1
npm info ok
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.9.4
npm info ok
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.9.4
npm info lifecycle dash-renderer@0.13.1~prebuild-prod: dash-renderer@0.13.1
npm info lifecycle dash-renderer@0.13.1~build-prod: dash-renderer@0.13.1

> dash-renderer@0.13.1 build-prod C:\dev\Daedalus\lib\dash-renderer
> cross-env NODE_ENV=production node node_modules/.bin/webpack --config=config/webpack.config.prod.js

C:\dev\Daedalus\lib\dash-renderer\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at notFoundError (C:\dev\Daedalus\lib\dash-renderer\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\dev\Daedalus\lib\dash-renderer\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\dev\Daedalus\lib\dash-renderer\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm info lifecycle dash-renderer@0.13.1~build-prod: Failed to exec build-prod script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dash-renderer@0.13.1 build-prod: `cross-env NODE_ENV=production node node_modules/.bin/webpack --config=config/webpack.config.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dash-renderer@0.13.1 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-07-26T18_57_34_933Z-debug.log
npm info lifecycle dash-renderer@0.13.1~prepublish: Failed to exec prepublish script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dash-renderer@0.13.1 prepublish: `npm test && npm run build-prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dash-renderer@0.13.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-07-26T18_57_34_971Z-debug.log

```

**Comment by alexcjohnson** [comment]
@Mnuzz apologies that nobody responded to this issue! On first glance it looks like it's happening outside of our code... hopefully that (and the fact that we haven't heard any more about this since your post) means it's been solved elsewhere? Anyway we're merging `dash-renderer` into the `dash` repo, so if you (or any other Windows users) hit this issue again, please open a new issue over there.
